package GUI;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JButton;

/**
 * Status: Passed
 * @author tanh2k2k
 */
public class FrameCalculator extends javax.swing.JFrame {

    /* ============================= VARIABLES ============================= */
    private boolean canAppend = false;          // check appending
    private boolean isError = false;            // check ERROR screen appear
    private double num = 0;                     // input number
    private double memory = 0;                  // number save in mêmory
    String operator = "";                       // basic operators

    /* ============================ CONSTRUCTOR ============================ */
    /**
     * Creates new form FrameCalculator
     */
    public FrameCalculator() {
        FlatIntelliJLaf.install();
        initComponents();
    }

    /* ============================== FUNCTION ============================== */
    /**
     * Allow user press numeric button (1, 2, 3, 4, 5, 6, 7, 8, 9)
     *
     * @param button Numeric button
     */
    private void pressBtnNum(JButton button) {
        if (!isError) {
            if (txtDisplay.getText().equals("0") || !canAppend)
                txtDisplay.setText(button.getText());
            else
                txtDisplay.setText(txtDisplay.getText() + button.getText());
            canAppend = true;
        }
    }

    /**
     * Allow user press basic operator button (+, -, *, /)
     *
     * @param button Operator button
     */
    private void pressBtnOperator(JButton button) {
        if (!isError) {
            if (canAppend && operator.equals("")) {
                num = Double.parseDouble(txtDisplay.getText());
                operator = button.getText();
            } else if (canAppend && !operator.equals("")) {
                pressBtnResult();
                operator = button.getText();
            } else
                operator = button.getText();
            canAppend = false;
        }
    }

    /**
     * Allow user press Result button ( = ) and show result
     */
    private void pressBtnResult() {
        if (canAppend && !isError)
            if (operator.isEmpty()) {
                num = Double.parseDouble(txtDisplay.getText());
                txtDisplay.setText(convertDecimalFormat(num));
            }
        if (operator.equals("+")) {
            num += Double.parseDouble(txtDisplay.getText());
            txtDisplay.setText(convertDecimalFormat(num));
        } else if (operator.equals("-")) {
            num -= Double.parseDouble(txtDisplay.getText());
            txtDisplay.setText(convertDecimalFormat(num));
        } else if (operator.equals("*")) {
            num *= Double.parseDouble(txtDisplay.getText());
            txtDisplay.setText(convertDecimalFormat(num));
        } else if (operator.equals("/"))
            if (Double.parseDouble(txtDisplay.getText()) == 0) {
                txtDisplay.setText("ERROR");
                isError = true;
            } else {
                num /= Double.parseDouble(txtDisplay.getText());
                txtDisplay.setText(convertDecimalFormat(num));
            }
        operator = "";
        canAppend = false;
        System.out.println("RESULT = " + num);
    }

    /**
     * covert Double variable to String
     *
     * @param num Input number
     * @return Double number is String
     */
    private String convertDecimalFormat(double num) {
        Locale locale = new Locale("en", "UK");
        DecimalFormat dFormat = (DecimalFormat) NumberFormat.getNumberInstance(locale);
        String pattern = "#########.#########";
        dFormat.applyPattern(pattern);
        String result = dFormat.format(num);
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        paneBackground = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btnMClear = new javax.swing.JButton();
        btnMRecall = new javax.swing.JButton();
        btnMStore = new javax.swing.JButton();
        btnMAdd = new javax.swing.JButton();
        btnMSub = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnChangeSign = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btnInverse = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDecPoint = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setIconImages(null);
        setResizable(false);

        paneBackground.setBackground(new java.awt.Color(31, 32, 35));

        txtDisplay.setEditable(false);
        txtDisplay.setBackground(new java.awt.Color(44, 47, 49));
        txtDisplay.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtDisplay.setForeground(new java.awt.Color(255, 255, 255));
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("0");
        txtDisplay.setBorder(null);

        btnMClear.setBackground(new java.awt.Color(31, 32, 35));
        btnMClear.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnMClear.setForeground(new java.awt.Color(42, 222, 159));
        btnMClear.setText("MC");
        btnMClear.setBorderPainted(false);
        btnMClear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMClear.setOpaque(false);
        btnMClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMClearActionPerformed(evt);
            }
        });

        btnMRecall.setBackground(new java.awt.Color(31, 32, 35));
        btnMRecall.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnMRecall.setForeground(new java.awt.Color(42, 222, 159));
        btnMRecall.setText("MR");
        btnMRecall.setBorderPainted(false);
        btnMRecall.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMRecall.setOpaque(false);
        btnMRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRecallActionPerformed(evt);
            }
        });

        btnMStore.setBackground(new java.awt.Color(31, 32, 35));
        btnMStore.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnMStore.setForeground(new java.awt.Color(42, 222, 159));
        btnMStore.setText("MS");
        btnMStore.setBorderPainted(false);
        btnMStore.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMStore.setOpaque(false);
        btnMStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMStoreActionPerformed(evt);
            }
        });

        btnMAdd.setBackground(new java.awt.Color(31, 32, 35));
        btnMAdd.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnMAdd.setForeground(new java.awt.Color(42, 222, 159));
        btnMAdd.setText("M+");
        btnMAdd.setBorderPainted(false);
        btnMAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMAdd.setOpaque(false);
        btnMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAddActionPerformed(evt);
            }
        });

        btnMSub.setBackground(new java.awt.Color(31, 32, 35));
        btnMSub.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnMSub.setForeground(new java.awt.Color(42, 222, 159));
        btnMSub.setText("M-");
        btnMSub.setBorderPainted(false);
        btnMSub.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMSub.setOpaque(false);
        btnMSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSubActionPerformed(evt);
            }
        });

        btnSqrt.setBackground(new java.awt.Color(31, 32, 35));
        btnSqrt.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnSqrt.setForeground(new java.awt.Color(173, 172, 180));
        btnSqrt.setText("√");
        btnSqrt.setBorderPainted(false);
        btnSqrt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSqrt.setOpaque(false);
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        btnChangeSign.setBackground(new java.awt.Color(31, 32, 35));
        btnChangeSign.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnChangeSign.setForeground(new java.awt.Color(173, 172, 180));
        btnChangeSign.setText("±");
        btnChangeSign.setBorderPainted(false);
        btnChangeSign.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnChangeSign.setOpaque(false);
        btnChangeSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeSignActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(31, 32, 35));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnClear.setForeground(new java.awt.Color(173, 172, 180));
        btnClear.setText("C");
        btnClear.setBorderPainted(false);
        btnClear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClear.setOpaque(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBackspace.setBackground(new java.awt.Color(31, 32, 35));
        btnBackspace.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnBackspace.setForeground(new java.awt.Color(173, 172, 180));
        btnBackspace.setText("←");
        btnBackspace.setBorderPainted(false);
        btnBackspace.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBackspace.setOpaque(false);
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(31, 32, 35));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorderPainted(false);
        btn7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn7.setOpaque(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(31, 32, 35));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorderPainted(false);
        btn8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn8.setOpaque(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(31, 32, 35));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorderPainted(false);
        btn9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn9.setOpaque(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(31, 32, 35));
        btnDiv.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(173, 172, 180));
        btnDiv.setText("/");
        btnDiv.setBorderPainted(false);
        btnDiv.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDiv.setOpaque(false);
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnPercent.setBackground(new java.awt.Color(31, 32, 35));
        btnPercent.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnPercent.setForeground(new java.awt.Color(173, 172, 180));
        btnPercent.setText("%");
        btnPercent.setBorderPainted(false);
        btnPercent.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPercent.setOpaque(false);
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });

        btnInverse.setBackground(new java.awt.Color(31, 32, 35));
        btnInverse.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnInverse.setForeground(new java.awt.Color(173, 172, 180));
        btnInverse.setText("1/x");
        btnInverse.setBorderPainted(false);
        btnInverse.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnInverse.setOpaque(false);
        btnInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInverseActionPerformed(evt);
            }
        });

        btnMul.setBackground(new java.awt.Color(31, 32, 35));
        btnMul.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnMul.setForeground(new java.awt.Color(173, 172, 180));
        btnMul.setText("*");
        btnMul.setBorderPainted(false);
        btnMul.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMul.setOpaque(false);
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(31, 32, 35));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorderPainted(false);
        btn6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn6.setOpaque(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(31, 32, 35));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorderPainted(false);
        btn5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn5.setOpaque(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(31, 32, 35));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorderPainted(false);
        btn4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn4.setOpaque(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(31, 32, 35));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorderPainted(false);
        btn1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn1.setOpaque(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(31, 32, 35));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorderPainted(false);
        btn2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn2.setOpaque(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(31, 32, 35));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorderPainted(false);
        btn3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn3.setOpaque(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnSub.setBackground(new java.awt.Color(31, 32, 35));
        btnSub.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnSub.setForeground(new java.awt.Color(173, 172, 180));
        btnSub.setText("-");
        btnSub.setBorderPainted(false);
        btnSub.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSub.setOpaque(false);
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btnResult.setBackground(new java.awt.Color(31, 32, 35));
        btnResult.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnResult.setForeground(new java.awt.Color(42, 222, 159));
        btnResult.setText("=");
        btnResult.setBorderPainted(false);
        btnResult.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnResult.setOpaque(false);
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(31, 32, 35));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(173, 172, 180));
        btnAdd.setText("+");
        btnAdd.setBorderPainted(false);
        btnAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdd.setOpaque(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDecPoint.setBackground(new java.awt.Color(31, 32, 35));
        btnDecPoint.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnDecPoint.setForeground(new java.awt.Color(255, 255, 255));
        btnDecPoint.setText(".");
        btnDecPoint.setBorderPainted(false);
        btnDecPoint.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDecPoint.setOpaque(false);
        btnDecPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecPointActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(31, 32, 35));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorderPainted(false);
        btn0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn0.setOpaque(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBackgroundLayout = new javax.swing.GroupLayout(paneBackground);
        paneBackground.setLayout(paneBackgroundLayout);
        paneBackgroundLayout.setHorizontalGroup(
                paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneBackgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(paneBackgroundLayout.createSequentialGroup()
                                                        .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(paneBackgroundLayout.createSequentialGroup()
                                                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(paneBackgroundLayout.createSequentialGroup()
                                                                        .addComponent(btnDecPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(paneBackgroundLayout.createSequentialGroup()
                                                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(paneBackgroundLayout.createSequentialGroup()
                                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createSequentialGroup()
                                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createSequentialGroup()
                                                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnChangeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createSequentialGroup()
                                                .addComponent(btnMClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnMRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnMStore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnMSub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneBackgroundLayout.setVerticalGroup(
                paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneBackgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnMClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMStore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMSub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnChangeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(paneBackgroundLayout.createSequentialGroup()
                                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnDecPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paneBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paneBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    // ===================== VARIABLE =====================
    // ZERO
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn0);
    }

    // ONE
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn1);
    }

    // TWO
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn2);
    }

    // THREE
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn3);
    }

    // FOUR
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn4);
    }

    // FIVE
    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn5);
    }

    // SIX
    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn6);
    }

    // SEVEN
    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn7);
    }

    // EIGHT
    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn8);
    }

    // NINE
    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnNum(btn9);
    }

    // DECIMAL POINT
    private void btnDecPointActionPerformed(java.awt.event.ActionEvent evt) {
        if (!txtDisplay.getText().contains(".") && canAppend && !isError)
            txtDisplay.setText(txtDisplay.getText() + ".");
    }

    // ===================== OPERATIONS =====================
    // ADDITION
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnOperator(btnAdd);
    }

    // SUBTRACTION
    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnOperator(btnSub);
    }

    // MULTIPLICATION
    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnOperator(btnMul);
    }

    // DIVISION
    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnOperator(btnDiv);
    }

    // INVERSE
    private void btnInverseActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError)
            if (Double.parseDouble(txtDisplay.getText()) == 0) {
                txtDisplay.setText("ERROR");
                isError = true;
            } else {
                txtDisplay.setText(convertDecimalFormat(1 / (Double.parseDouble(txtDisplay.getText()))));
                canAppend = false;
            }
    }

    // PERCENT
    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError) {
            txtDisplay.setText(convertDecimalFormat(Double.parseDouble(txtDisplay.getText()) / 100));
            canAppend = false;
        }
    }

    // SQUARE
    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError) {
            if (Double.parseDouble(txtDisplay.getText()) < 0) {
                txtDisplay.setText("ERROR");
                isError = true;
            } else
                txtDisplay.setText(convertDecimalFormat(Math.sqrt(Double.parseDouble(txtDisplay.getText()))));
            canAppend = false;
        }
    }

    // CHANGE SIGN
    private void btnChangeSignActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError) {
            String result = txtDisplay.getText();
            if (canAppend && !result.equals("0"))
                if (result.charAt(0) != '-')
                    result = "-" + result;
                else
                    result = result.substring(1, result.length());
            if (!canAppend) {
                result = convertDecimalFormat(Double.parseDouble(result) * (-1));
                num = Double.parseDouble(result) * (-1);
            }
            txtDisplay.setText(result);
        }
    }

    // BACKSPACE
    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {
        if (canAppend && !isError) {
            String result = txtDisplay.getText();
            int length = result.length();
            System.out.println(length);
            if (length > 3)
                if ((result.charAt(length - 1) + "").equals("."))
                    result = result.substring(0, length - 2);
                else
                    result = result.substring(0, length - 1);
            else if (length == 3)
                if (result.charAt(0) == '-' && result.charAt(2) == '.')
                    result = "0";
                else if ((result.charAt(length - 1) + "").equals("."))
                    result = result.substring(0, length - 2);
                else
                    result = result.substring(0, 2);
            else if (length == 2)
                if (result.charAt(0) == '-' || result.charAt(1) == '.')
                    result = "0";
                else
                    result = result.substring(0, 1);
            else
                result = "0";
            txtDisplay.setText(result);
        }
    }//GEN-LAST:event_btnBackspaceActionPerformed

    // CLEAR
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClearActionPerformed
    {//GEN-HEADEREND:event_btnClearActionPerformed
        num = 0;
        operator = "";
        canAppend = false;
        isError = false;
        txtDisplay.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    // ===================== CALCULATIONS =====================
    // RESULT
    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {
        pressBtnResult();
    }

    // MEMORY CLEAR
    private void btnMClearActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError) {
            memory = 0;
            canAppend = false;
        }
    }

    // MEMORY RECALL
    private void btnMRecallActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError) {
            txtDisplay.setText(convertDecimalFormat(memory));
            canAppend = false;
        }
    }

    // MEMORY STORE
    private void btnMStoreActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError) {
            memory = Double.parseDouble(txtDisplay.getText());
            canAppend = false;
        }
    }

    // MEMORY ADDITION
    private void btnMAddActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError) {
            memory += Double.parseDouble(txtDisplay.getText());
            canAppend = false;
        }
    }

    // MEMORY SUBTRACTION
    private void btnMSubActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isError) {
            memory -= Double.parseDouble(txtDisplay.getText());
            canAppend = false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCalculator().setVisible(true);
            }
        });
    }

    // ===================== VARIABLES =====================
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnChangeSign;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDecPoint;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnInverse;
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMClear;
    private javax.swing.JButton btnMRecall;
    private javax.swing.JButton btnMStore;
    private javax.swing.JButton btnMSub;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSub;
    private javax.swing.JPanel paneBackground;
    private javax.swing.JTextField txtDisplay;
}
